const GET_REQUEST = 'GET_REQUEST';
const GET_SUCCESS = 'GET_SUCCESS';
const GET_FAIL = 'GET_FAIL';

const USER_SIGNIN = 'USER_SIGNIN';
const USER_SIGNOUT = 'USER_SIGNOUT';

const REMOVED_FROM_LIST = 'REMOVED_FROM_LIST';
const ADDED_TO_LIST = 'ADDED_TO_LIST'

export {
  GET_FAIL,
  GET_SUCCESS,
  GET_REQUEST,
  USER_SIGNIN,
  USER_SIGNOUT,
  REMOVED_FROM_LIST,
  ADDED_TO_LIST
};
